import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '../styles/Home.module.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shop Pay</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="./public/favicon.ico" />
      </Head>
      <h1>Welcome</h1>
    </div>
  );
}
